{
    "page_links": [
        "/Plan Setup Reference/WEBS Setup.htm",
        "/Plan Setup Reference/Using_the_site.htm",
        "/Plan Setup Reference/CompanySetup/Company Setup.htm",
        "/Plan Setup Reference/CompanySetup/Company Divisions.htm",
        "/Plan Setup Reference/CompanySetup/Add_Edit_Division_Window.htm",
        "/Plan Setup Reference/PlanSetup/Plan Setup.htm",
        "/Plan Setup Reference/PlanSetup/Benefit Plans.htm",
        "/Plan Setup Reference/PlanSetup/adding_a_new_Plan.htm",
        "/Plan Setup Reference/PlanSetup/DuplicatingAPlan.htm",
        "/Plan Setup Reference/PlanSetup/BenefitPlanAccessRights.htm",
        "/Plan Setup Reference/Employment status codes.htm",
        "/Plan Setup Reference/PlanSetup/Dictionary.htm",
        "/Plan Setup Reference/PlanSetup/Past, Current, and Future benefit plans.htm",
        "/Plan Setup Reference/PlanSetup/DownloadBenefitRates.htm",
        "/Plan Setup Reference/PlanSetup/UploadBenefitRates.htm",
        "/Plan Setup Reference/PlanSetup/Add year.htm",
        "/Plan Setup Reference/PlanSetup/AddYearToPlans.htm",
        "/Plan Setup Reference/PlanConfiguration/PlanConfiguration.htm",
        "/Plan Setup Reference/Plan_Description_tab.htm",
        "/Plan Setup Reference/PlanConfiguration/SmokerDeclaration.htm",
        "/Plan Setup Reference/Health_coverage_tab.htm",
        "/Plan Setup Reference/PlanConfiguration/Configure_Health_Coverage_win.htm",
        "/Plan Setup Reference/Lock in expiry.htm",
        "/Plan Setup Reference/ConfigHealth_cov_opt_win.htm",
        "/Plan Setup Reference/PlanConfiguration/CaptureAltCoverage.htm",
        "/Plan Setup Reference/PlanConfiguration/AltCoverageTable.htm",
        "/Plan Setup Reference/PlanConfiguration/AltCoverageContinued.htm",
        "/Plan Setup Reference/Life_benefits_tab.htm",
        "/Plan Setup Reference/PlanConfiguration/Configure_Life_Coverage_Item_window.htm",
        "/Plan Setup Reference/PlanConfiguration/Life-Multiple_options.htm",
        "/Plan Setup Reference/PlanConfiguration/Option coverage.htm",
        "/Plan Setup Reference/PlanConfiguration/UnitCoverage.htm",
        "/Plan Setup Reference/Multiple Options Configuration Window.htm",
        "/Plan Setup Reference/PlanConfiguration/CommonParams.htm",
        "/Plan Setup Reference/PlanConfiguration/Calculation_type.htm",
        "/Plan Setup Reference/PlanConfiguration/Coverage_Termination_Rules.htm",
        "/Plan Setup Reference/PlanConfiguration/NEM.htm",
        "/Plan Setup Reference/PlanConfiguration/Employer_benefit_opt_contrib.htm",
        "/Plan Setup Reference/PlanSetup/Age Reduction.htm",
        "/Plan Setup Reference/Life Insurance Rate Tables.htm",
        "/Plan Setup Reference/PlanConfiguration/combined_max.htm",
        "/Plan Setup Reference/single_link_benefits.htm",
        "/Plan Setup Reference/elect_max_option.htm",
        "/Plan Setup Reference/PlanConfiguration/Disability_Coverage_tab.htm",
        "/Plan Setup Reference/PlanConfiguration/Configure Long Term Disability.htm",
        "/Plan Setup Reference/DisabilityOptionWindow.htm",
        "/Plan Setup Reference/PlanConfiguration/disabilityGrading.htm",
        "/Plan Setup Reference/PlanConfiguration/LTD Rate tables.htm",
        "/Plan Setup Reference/PlanConfiguration/Credit Benefits tab.htm",
        "/Plan Setup Reference/Configure Credit Benefit coverage.htm",
        "/Plan Setup Reference/PlanConfiguration/Vacation Buy Sell.htm",
        "/Plan Setup Reference/PlanConfiguration/Benefits_Ordering.htm",
        "/Plan Setup Reference/PlanConfiguration/Company Contributions.htm",
        "/Plan Setup Reference/Unused Flex tab.htm",
        "/Plan Setup Reference/PlanConfiguration/Configure Unused Flex.htm",
        "/Plan Setup Reference/ProrationOfExcessFlex.htm",
        "/Plan Setup Reference/PlanConfiguration/AcctContribution.htm",
        "/Plan Setup Reference/PlanConfiguration/Wellness Credits.htm",
        "/Plan Setup Reference/New Question window.htm",
        "/Plan Setup Reference/PlanConfiguration/Benefit_packages.htm",
        "/Plan Setup Reference/PlanConfiguration/Configure_benefit_packages_window.htm",
        "/Plan Setup Reference/Configure Package.htm",
        "/Plan Setup Reference/PlanSetup/CurrentAndFuturePackages.htm",
        "/Plan Setup Reference/Enrollment Setup tab.htm",
        "/Plan Setup Reference/Edit Enrollment Step window.htm",
        "/Annual Enrollment Guide/Annual Enrollment_setup.htm",
        "/Annual Enrollment Guide/Preparation for the Annual.htm",
        "/Annual Enrollment Guide/Add the next year in Plan Setup (Add Year).htm",
        "/Annual Enrollment Guide/Make changes in Plan setup.htm",
        "/Annual Enrollment Guide/ExcessFlex.htm",
        "/Plan Setup Reference/PlanSetup/DownloadBenefitRates.htm",
        "/Plan Setup Reference/PlanSetup/UploadBenefitRates.htm",
        "/Annual Enrollment Guide/ReviewBenefitRates.htm",
        "/Annual Enrollment Guide/Create payroll schedules for new plan year.htm",
        "/Annual Enrollment Guide/ConfigYTDreport.htm",
        "/Annual Enrollment Guide/CopyYTDConfig.htm",
        "/Annual Enrollment Guide/VerifyUpdateCurrentEarnings.htm",
        "/Annual Enrollment Guide/CreateEmployeePinMailers.htm",
        "/Annual Enrollment Guide/ReviewEnrollmentEmailContent.htm",
        "/Annual Enrollment Guide/Complete Pre Enrollment Activities.htm",
        "/Annual Enrollment Guide/FreezeCurrentEarnings.htm",
        "/Annual Enrollment Guide/PrecalculateFutureOptions.htm",
        "/Annual Enrollment Guide/Pre-enrollmentTesting.htm",
        "/Annual Enrollment Guide/LoadPlanDetailsEtc.htm",
        "/Annual Enrollment Guide/SetTheEnrollmentWindow.htm",
        "/BeneficiaryMgmt_eSig/Intro.htm",
        "/BeneficiaryMgmt_eSig/beneficiary_types.htm",
        "/BeneficiaryMgmt_eSig/LabelPrimaryBeneficiary.htm",
        "/Employee Admin Ref/deleted/Beneficiary Restriction Configuration.htm",
        "/BeneficiaryMgmt_eSig/enable_e-beneficiary_designation.htm",
        "/BeneficiaryMgmt_eSig/CofiguringESignature.htm",
        "/BeneficiaryMgmt_eSig/EnablingTypeToSign.htm",
        "/BeneficiaryMgmt_eSig/config_esign_declaration_and_agreement_msg.htm",
        "/BeneficiaryMgmt_eSig/config_esignature_availability_province.htm",
        "/BeneficiaryMgmt_eSig/view_history_of_changes.htm",
        "/BeneficiaryMgmt_eSig/template_file.htm",
        "/BeneficiaryMgmt_eSig/GenericPlanSetup.htm",
        "/BeneficiaryMgmt_eSig/config_esign_plan_offerings.htm",
        "/BeneficiaryMgmt_eSig/ConfigForWetSig.htm",
        "/BeneficiaryMgmt_eSig/plan_setup.htm",
        "/BeneficiaryMgmt_eSig/config_beneficiary_form.htm",
        "/BeneficiaryMgmt_eSig/UpdateExistingPlans.htm",
        "/BeneficiaryMgmt_eSig/ConvertingEmployeesToElectronic.htm",
        "/BeneficiaryMgmt_eSig/EmployeesSignAndSave.htm",
        "/BeneficiaryMgmt_eSig/enable_contingent_beneficiary.htm",
        "/HRIS/Intro_HRIS.htm",
        "/HRIS/SystemOfRecord.htm",
        "/HRIS/File import process.htm",
        "/HRIS/HRISValidation.htm",
        "/HRIS/HRISComparison.htm",
        "/HRIS/HRISimport.htm",
        "/HRIS/ActionRequiredProcessing.htm",
        "/HRIS/HandlingCompoundRetroactiveChgs.htm",
        "/HRIS/OutofSequenceCompoundChgs.htm",
        "/HRIS/employee data changes.htm",
        "/HRIS/InsignificantChgs.htm",
        "/HRIS/SignificantChgs.htm",
        "/HRIS/ProcessingOrder.htm",
        "/HRIS/HRISsetup.htm",
        "/HRIS/ClientSpecificVariables.htm",
        "/HRIS/AutomatedStatusChg.htm",
        "/HRIS/SwitchPlan.htm",
        "/HRIS/Flexit Standard Format HRIS File.htm",
        "/HRIS/FileNamingConventions.htm",
        "/HRIS/HeaderFormat-127.htm",
        "/HRIS/RecordFormat-718.htm",
        "/HRIS/ImportantDetailsOfRecordFormat.htm",
        "/payroll_setup/EN/intro.htm",
        "/payroll_setup/EN/view_edit_payroll.htm",
        "/payroll_setup/EN/add_edit_payroll.htm",
        "/payroll_setup/EN/add_payroll.htm",
        "/payroll_setup/EN/View_edit_payroll_page.htm",
        "/payroll_setup/EN/duplicate_payroll.htm",
        "/payroll_setup/EN/delete_payroll.htm",
        "/payroll_setup/EN/set_up_payroll_schedule.htm",
        "/payroll_setup/EN/pay_period_type.htm",
        "/payroll_setup/EN/create_payroll_schedule.htm",
        "/payroll_setup/EN/select_year_to_view.htm",
        "/payroll_setup/EN/modify_sched.htm",
        "/payroll_setup/EN/add_future_sched.htm",
        "/payroll_setup/EN/bulk_add_future_pay_schedule.htm",
        "/payroll_setup/EN/sched_chg_next_year.htm",
        "/payroll_setup/EN/modify_sched_mid_year.htm",
        "/payroll_setup/EN/payroll_file_formats.htm",
        "/payroll_setup/EN/payroll_format_options.htm",
        "/payroll_setup/EN/std_payroll_types.htm",
        "/payroll_setup/EN/std_payroll_export_xml_format.htm",
        "/payroll_setup/EN/std_payroll_export_xml_schema.htm",
        "/payroll_setup/Payroll_format_text.htm",
        "/payroll_setup/EN/requirements_for_adp.htm",
        "/payroll_setup/EN/requirements_for_dfs.htm",
        "/payroll_setup/EN/add_edit_payroll_codes.htm",
        "/payroll_setup/EN/paycode_requirements.htm",
        "/payroll_setup/Add_Payroll.htm",
        "/payroll_setup/EN/edit_Payroll.htm",
        "/payroll_setup/EN/payroll_codes_chapter.htm",
        "/payroll_setup/EN/deduction.htm",
        "/payroll_setup/EN/deductions_life_benefits.htm",
        "/payroll_setup/EN/vacation_related_paycodes.htm",
        "/payroll_setup/EN/employer_paid_amount.htm",
        "/payroll_setup/EN/flex_credits_applied.htm",
        "/payroll_setup/EN/excess_flex_deduct.htm",
        "/payroll_setup/EN/vacation_codes.htm",
        "/payroll_setup/EN/fed_prov_tax_rel_codes.htm",
        "/payroll_setup/EN/new_fed_tax_ben_code.htm",
        "/payroll_setup/EN/new_prov_tax_ben_code.htm",
        "/payroll_setup/EN/sales_tax.htm",
        "/payroll_setup/EN/GST.htm",
        "/payroll_setup/EN/payroll_regen.htm",
        "/EmailGuide/EN/EmailIntroduction.htm",
        "/EmailGuide/EN/ConfigureEmail.htm",
        "/EmailGuide/EN/email_template_config.htm",
        "/EmailGuide/EN/SystemDefinedTemplate.htm",
        "/EmailGuide/EN/AddNewTemplate.htm",
        "/EmailGuide/EN/EmailEditor.htm",
        "/EmailGuide/EN/DefaultTemplate.htm",
        "/EmailGuide/EN/PlanOverride.htm",
        "/EmailGuide/EN/DivisionOverride.htm",
        "/EmailGuide/EN/DeleteTemplate.htm",
        "/EmailGuide/EN/SendEmails.htm",
        "/EmailGuide/EN/EmailTheseEmployees.htm",
        "/EmailGuide/EN/ScheduledEmail.htm",
        "/EmailGuide/EN/setSchedule.htm",
        "/EmailGuide/EN/Filter.htm",
        "/EmailGuide/EN/Legacy_Email_config.htm",
        "/EmailGuide/EN/ConfiguringEmailsPlanDictionary.htm",
        "/EmailGuide/EN/ConfiguringEmailsAppDictionary.htm",
        "/EmailGuide/EN/ConfigEmailCSV.htm",
        "/EmailGuide/EN/EmployeeConfigEmailsinCSV.htm",
        "/EmailGuide/EN/AdminConfigEmailsinCSV.htm",
        "/EmailGuide/EN/CompanySetup_newHire.htm",
        "/EmailGuide/EN/HomePage.htm",
        "/EmailGuide/EN/FormatMenu.htm",
        "/EmailGuide/EN/listOfEmails.htm",
        "/EmailGuide/EN/Placeholders.htm",
        "/Template_Guide/Intro.htm",
        "/Template_Guide/open_template_editor.htm",
        "/Template_Guide/TemplateEditor.htm",
        "/Template_Guide/Manage Files_Images.htm",
        "/Template_Guide/Images.htm",
        "/Template_Guide/LegacyTemplateProcess.htm",
        "/Template_Guide/EOIoverview.htm",
        "/Template_Guide/default_eoi_templates.htm",
        "/Template_Guide/Province override.htm",
        "/Template_Guide/EditEOITemplate.htm",
        "/Template_Guide/BenefitOverride.htm",
        "/Template_Guide/CarrierOverride.htm",
        "/Template_Guide/Legacy_EOI_template.htm",
        "/Template_Guide/PinReset_parent.htm",
        "/Template_Guide/Pin Reset.htm",
        "/Template_Guide/ResetPin.htm",
        "/Template_Guide/PinResetHistory.htm",
        "/Template_Guide/Beneficiary Form.htm",
        "/Template_Guide/EditBeneficiaryTemplate.htm",
        "/Template_Guide/ProvinceOverride.htm",
        "/Template_Guide/Triggering Beneficiary form.htm",
        "/Template_Guide/ElectronicBeneficiaryDesignation.htm",
        "/Template_Guide/ElectronicFile.htm",
        "/Template_Guide/PlaceholdersTable-Wide.htm",
        "/Template_Guide/special_considerations.htm",
        "/Template_Guide/Images.htm",
        "/BeneficiaryMgmt_eSig/template_file.htm",
        "/UploadFileGuide/AdminConfig.htm",
        "/Annual Enrollment Guide/Administrating Annual Enrollment.htm",
        "/Annual Enrollment Guide/Enrollment Period Support.htm",
        "/Annual Enrollment Guide/ConfigEnrollNotification.htm",
        "/Annual Enrollment Guide/ProvideSupportToEmployees.htm",
        "/Annual Enrollment Guide/WarnClientReWaitingPeriods.htm",
        "/Annual Enrollment Guide/HRIS.htm",
        "/Annual Enrollment Guide/Annual enrollment.htm",
        "/Annual Enrollment Guide/LifeEvents.htm",
        "/Annual Enrollment Guide/NewHires.htm",
        "/Annual Enrollment Guide/MOnitorEnrollmentProgression.htm",
        "/Annual Enrollment Guide/MOnitorUsingManageEmployees.htm",
        "/Annual Enrollment Guide/MOnitorUsingExtracts.htm",
        "/Annual Enrollment Guide/ExtendEnrollmentPeriod.htm",
        "/Annual Enrollment Guide/Transferring Black out Activities.htm",
        "/Annual Enrollment Guide/CompleteCurrentYearProcessing.htm",
        "/Annual Enrollment Guide/DefaultIncompleteEnrollments.htm",
        "/Annual Enrollment Guide/TransferEnrollments.htm",
        "/Annual Enrollment Guide/Run_payroll_after_transfer.htm",
        "/Annual Enrollment Guide/MaintainBlackout.htm",
        "/Annual Enrollment Guide/Unlock Member Site and Resume.htm",
        "/Annual Enrollment Guide/Annual Enrollment Timeline.htm",
        "/Annual Enrollment Guide/Checklist for Enrollment Activities.htm",
        "/Employee Admin Ref/Introduction.htm",
        "/Employee Admin Ref/add_employee_chapter.htm",
        "/Employee Admin Ref/AddNewEmployee-online.htm",
        "/Employee Admin Ref/waiting_period.htm",
        "/Employee Admin Ref/csvs_for_newhire.htm",
        "/Employee Admin Ref/employee_tab.htm",
        "/Employee Admin Ref/view_new_employee.htm",
        "/Employee Admin Ref/assign_pin.htm",
        "/Employee Admin Ref/default_enrollment.htm",
        "/Employee Admin Ref/online_enrollment_employee_eroll.htm",
        "/Employee Admin Ref/LoginAsEmployeeViaAdmin.htm",
        "/Employee Admin Ref/Print a Confirmation Statement.htm",
        "/Employee Admin Ref/enroll_for_employee.htm",
        "/Employee Admin Ref/add_another.htm",
        "/Employee Admin Ref/Add an Employee with a Future.htm",
        "/Employee Admin Ref/modify_employee_chapter.htm",
        "/Employee Admin Ref/OpenEmployeeAdmin.htm",
        "/Employee Admin Ref/modify_employee.htm",
        "/Employee Admin Ref/Switch Divisions for an Employee.htm",
        "/Employee Admin Ref/passthrough_override.htm",
        "/Employee Admin Ref/Change Employee Status.htm",
        "/Employee Admin Ref/Terminate an Employee using.htm",
        "/Employee Admin Ref/Modify Employee Effective.htm",
        "/Employee Admin Ref/recalculate.htm",
        "/Employee Admin Ref/precalculate.htm",
        "/Employee Admin Ref/send_emails_to_employees.htm",
        "/Employee Admin Ref/Modify Employee Benefits.htm",
        "/Employee Admin Ref/EOI_required.htm",
        "/Employee Admin Ref/update_dependent_coverage.htm",
        "/Employee Admin Ref/Flex.htm",
        "/Employee Admin Ref/update_flex_dollars.htm",
        "/Employee Admin Ref/update_additional_credit.htm",
        "/Employee Admin Ref/config_acct_contribution.htm",
        "/Employee Admin Ref/update_wellness_credit.htm",
        "/Employee Admin Ref/setup_for_next_year.htm",
        "/Employee Admin Ref/FlexCreditBenefit.htm",
        "/Employee Admin Ref/update_flex_credits.htm",
        "/Employee Admin Ref/configure_account_contributions.htm",
        "/Employee Admin Ref/flex_credit_additional.htm",
        "/Employee Admin Ref/flex_credit_next_plan_year.htm",
        "/Employee Admin Ref/Override Coverage.htm",
        "/Employee Admin Ref/reductionOverride.htm",
        "/Employee Admin Ref/Coverage Override.htm",
        "/Employee Admin Ref/ManualAdj.htm",
        "/Employee Admin Ref/How to enter Manual Adjustment.htm",
        "/Employee Admin Ref/PayrollAdj.htm",
        "/Employee Admin Ref/How to enter Manual Adjustment_1.htm",
        "/Employee Admin Ref/PremiumAdj.htm",
        "/Employee Admin Ref/Add Edit or Remove Dependents.htm",
        "/Employee Admin Ref/addDependents.htm",
        "/Employee Admin Ref/Edit Dependents.htm",
        "/Employee Admin Ref/Inactivate Dependents.htm",
        "/Employee Admin Ref/activate_dependent.htm",
        "/Employee Admin Ref/recertify_student.htm",
        "/Employee Admin Ref/update_smoker_status_for_dependent.htm",
        "/Employee Admin Ref/print_conf_statement.htm",
        "/Employee Admin Ref/BeneficiaryMgt.htm",
        "/Employee Admin Ref/check_beneficiary_reqs.htm",
        "/Employee Admin Ref/PrintBeneficiaryForm.htm",
        "/Employee Admin Ref/PrintElectronicBeneficiaryDeclaration.htm",
        "/Employee Admin Ref/manage_eoi.htm",
        "/Employee Admin Ref/manage_eoi_related_forms.htm",
        "/Employee Admin Ref/confirm_eoi.htm",
        "/Employee Admin Ref/FileUpload.htm",
        "/Employee Admin Ref/AddComments.htm",
        "/Employee Admin Ref/ManageEmployeesPage.htm",
        "/Employee Admin Ref/manage_employee.htm",
        "/Employee Admin Ref/FindEmployee.htm",
        "/Employee Admin Ref/search_filter_n_settings.htm",
        "/Employee Admin Ref/predefined_filters.htm",
        "/Employee Admin Ref/ResetPin-New!.htm",
        "/Employee Admin Ref/ResetPINAll.htm",
        "/Employee Admin Ref/ResetPINFiltered.htm",
        "/Employee Admin Ref/ResetPINEmployee.htm",
        "/Employee Admin Ref/csvs_for_pins.htm",
        "/Employee Admin Ref/Unlock an Employee.htm",
        "/Employee Admin Ref/ReinstateUsingManageEmployeePage.htm",
        "/Employee Admin Ref/Audits.htm",
        "/Employee Admin Ref/Audit-new.htm",
        "/Employee Admin Ref/legacy_audits.htm",
        "/Employee Admin Ref/audits_login.htm",
        "/Employee Admin Ref/Verify Actions for an Employee.htm",
        "/Employee Admin Ref/ManageInBulk.htm",
        "/Employee Admin Ref/Manage Billing Screen.htm",
        "/Employee Admin Ref/Export a Carrier.htm",
        "/Employee Admin Ref/Export a Payroll.htm",
        "/Employee Admin Ref/Payroll_code_ytd_report.htm",
        "/Employee Admin Ref/GeneratingDataExtracts.htm",
        "/Employee Admin Ref/Retrieving Data Extracts.htm",
        "/Employee Admin Ref/Check for Jobs in the Offline.htm",
        "/Employee Admin Ref/mass_salary_update.htm",
        "/Employee Admin Ref/recalculate_employees_in_bulk.htm",
        "/Employee Admin Ref/pending_act_hris_import_log.htm",
        "/BeneficiaryMgmt_eSig/Admin_site_Beneficiaries.htm",
        "/BeneficiaryMgmt_eSig/pending_beneficiaries.htm",
        "/BeneficiaryMgmt_eSig/IrrevocableBeneficiaries.htm",
        "/BeneficiaryMgmt_eSig/WetSig.htm",
        "/BeneficiaryMgmt_eSig/OngoingAdminSupport.htm",
        "/BeneficiaryMgmt_eSig/del_beneficiary.htm",
        "/BeneficiaryMgmt_eSig/AddBene.htm",
        "/BeneficiaryMgmt_eSig/Print_forms.htm",
        "/BeneficiaryMgmt_eSig/eBeneficiary.htm",
        "/BeneficiaryMgmt_eSig/Audit.htm",
        "/BeneficiaryMgmt_eSig/beneficiary_extract.htm",
        "/BeneficiaryMgmt_eSig/annual_maintenance.htm",
        "/HRIS/Intro_HRIS.htm",
        "/HRIS/SystemOfRecord.htm",
        "/HRIS/FileNamingConventions.htm",
        "/HRIS/File import process.htm",
        "/HRIS/HRISValidation.htm",
        "/HRIS/HRISComparison.htm",
        "/HRIS/HRISimport.htm",
        "/HRIS/ActionRequiredProcessing.htm",
        "/HRIS/HandlingCompoundRetroactiveChgs.htm",
        "/HRIS/OutofSequenceCompoundChgs.htm",
        "/HRIS/employee data changes.htm",
        "/HRIS/InsignificantChgs.htm",
        "/HRIS/SignificantChgs.htm",
        "/HRIS/Employment Status Codes.htm",
        "/HRIS/CngAnEmployeesStatus.htm",
        "/HRIS/AutomatedStatusChg.htm",
        "/HRIS/SwitchPlan.htm",
        "/HRIS/ProcessingOrder.htm",
        "/HRIS/EmploymentStatusChgs-Ex.htm",
        "/HRIS/HRISsetup.htm",
        "/HRIS/Flexit Standard Format HRIS File.htm",
        "/HRIS/CommonErrors.htm",
        "/HRIS/Employment Status Code Changes.htm",
        "/OfflineTasks/DescriptionOfOfflineTasks.htm",
        "/OfflineTasks/Task/Task 111 Default New Hire enrollment.htm",
        "/OfflineTasks/Task/Task 300 New Student Notification Request.htm",
        "/OfflineTasks/Task/Task 301 Existing Student Notification Request.htm",
        "/OfflineTasks/Task/Task 302 Terminate Coverage for Overage Students.htm",
        "/OfflineTasks/Task/Task 303 Terminate coverage for dependents with expiry date.htm",
        "/OfflineTasks/Task/Task 304 Overage children certification required notification.htm",
        "/OfflineTasks/Task/Task 310 EOI Pending Cancellation Job.htm",
        "/OfflineTasks/Task/Task 320 Beneficiary Pending Cancellation Job.htm",
        "/OfflineTasks/Task/Task 400 Reduce coverage.htm",
        "/OfflineTasks/Task/Task 401 Terminate Benefits.htm",
        "/OfflineTasks/Task/Task 405 Automatically Terminate Benefits in the Future.htm",
        "/OfflineTasks/Task/Task 410 Password Expiry Notification.htm",
        "/UploadFileGuide/Intro.htm",
        "/UploadFileGuide/AddCategories.htm",
        "/UploadFileGuide/Admin.htm",
        "/UploadFileGuide/ManageEmployees.htm",
        "/UploadFileGuide/EmployeeAdmin.htm",
        "/EmailGuide/EN/EmailIntroduction.htm",
        "/EmailGuide/EN/SendEmails.htm",
        "/EmailGuide/EN/EmailTheseEmployees.htm",
        "/EmailGuide/EN/ScheduledEmail.htm",
        "/EmailGuide/EN/setSchedule.htm",
        "/EmailGuide/EN/Filter.htm",
        "/EmailGuide/EN/Legacy_Email_config.htm",
        "/EmailGuide/EN/ConfiguringEmailsPlanDictionary.htm",
        "/EmailGuide/EN/ConfiguringEmailsAppDictionary.htm",
        "/EmailGuide/EN/ConfigEmailCSV.htm",
        "/EmailGuide/EN/EmployeeConfigEmailsinCSV.htm",
        "/EmailGuide/EN/AdminConfigEmailsinCSV.htm",
        "/EmailGuide/EN/HomePage.htm",
        "/EmailGuide/EN/FormatMenu.htm",
        "/EmailGuide/EN/listOfEmails.htm",
        "/EmailGuide/EN/Placeholders.htm",
        "/Template_Guide/Triggering EOI form.htm",
        "/Template_Guide/ResetPin.htm",
        "/Template_Guide/Triggering Beneficiary form.htm",
        "/Web API/EN/swagger_doc.htm",
        "/Web API/EN/Global_admin_app.htm",
        "/Web API/EN/create_web_api.htm",
        "/Web API/EN/web_api_requests.htm",
        "/Web API/EN/api_response.htm",
        "/Web API/EN/rest_api_pagination.htm",
        "/BeneficiaryMgmt_eSig/Updating_beneficiaries_on_the_employee_Site.htm",
        "/BeneficiaryMgmt_eSig/ee_site.htm",
        "/BeneficiaryMgmt_eSig/beneficiary_update_from_home_page.htm",
        "/BeneficiaryMgmt_eSig/PartialEnrollment.htm",
        "/BeneficiaryMgmt_eSig/delete_beneficiary.htm",
        "/BeneficiaryMgmt_eSig/confirm_beneficiary.htm",
        "/UploadFileGuide/PlanMemberDocs.htm",
        "/UploadFileGuide/EEorLE.htm",
        "/UploadFileGuide/Anytime.htm",
        "/EmployeeSiteGuide/EN/Introduction.htm",
        "/EmployeeSiteGuide/EN/Audience.htm",
        "/EmployeeSiteGuide/EN/GettingSTarted.htm",
        "/EmployeeSiteGuide/EN/SysReqs.htm",
        "/EmployeeSiteGuide/EN/Accessing.htm",
        "/EmployeeSiteGuide/EN/initial_login_with_pin.htm",
        "/EmployeeSiteGuide/EN/HomePage.htm",
        "/EmployeeSiteGuide/EN/Views.htm",
        "/EmployeeSiteGuide/EN/CompletingYourEnrollment.htm",
        "/EmployeeSiteGuide/EN/return_to_enrollment.htm",
        "/EmployeeSiteGuide/EN/StartingTheEnrollmentProcess.htm",
        "/EmployeeSiteGuide/EN/Personal_info.htm",
        "/EmployeeSiteGuide/EN/Dependent_info.htm",
        "/EmployeeSiteGuide/EN/AddDependent.htm",
        "/EmployeeSiteGuide/EN/RemoveDependent.htm",
        "/EmployeeSiteGuide/EN/Wellness.htm",
        "/EmployeeSiteGuide/EN/Selecting_benefits.htm",
        "/EmployeeSiteGuide/EN/Health_type_benefits.htm",
        "/EmployeeSiteGuide/EN/LockIn.htm",
        "/EmployeeSiteGuide/EN/waive.htm",
        "/EmployeeSiteGuide/EN/ChangeDependentCvg.htm",
        "/EmployeeSiteGuide/EN/linked_health_benefits.htm",
        "/EmployeeSiteGuide/EN/step_up_down_rule.htm",
        "/EmployeeSiteGuide/EN/LifeIns.htm",
        "/EmployeeSiteGuide/EN/EOI.htm",
        "/EmployeeSiteGuide/EN/a_d_and_d.htm",
        "/EmployeeSiteGuide/EN/CriticalIllness.htm",
        "/EmployeeSiteGuide/EN/Disability.htm",
        "/EmployeeSiteGuide/EN/VacationBuySell.htm",
        "/EmployeeSiteGuide/EN/personal_wellness_days.htm",
        "/EmployeeSiteGuide/EN/Beneficiaries.htm",
        "/EmployeeSiteGuide/EN/beneficiaries_del.htm",
        "/EmployeeSiteGuide/EN/beneficiaries_home.htm",
        "/EmployeeSiteGuide/EN/allocating_funds.htm",
        "/EmployeeSiteGuide/EN/ExcessFlex.htm",
        "/EmployeeSiteGuide/EN/credit_reallocation.htm",
        "/EmployeeSiteGuide/EN/wellness_credits.htm",
        "/EmployeeSiteGuide/EN/personal_wellness_credit.htm",
        "/EmployeeSiteGuide/EN/Enrollment summary.htm",
        "/EmployeeSiteGuide/EN/ConfirmationScreen.htm",
        "/EmployeeSiteGuide/EN/electronic_beneficiary_confirmation.htm",
        "/EmployeeSiteGuide/EN/EnrollmentComplete.htm",
        "/EmployeeSiteGuide/EN/ConfirmationStatement.htm",
        "/EmployeeSiteGuide/EN/WetSig.htm",
        "/EmployeeSiteGuide/EN/UploadFiles.htm",
        "/EmployeeSiteGuide/EN/Life event.htm",
        "/EmployeeSiteGuide/EN/CreateLifeEvent.htm",
        "/EmployeeSiteGuide/EN/LE_during_AE.htm",
        "/EmployeeSiteGuide/EN/newHire.htm",
        "/EmployeeSiteGuide/EN/new_hire_outside_enrollment_pd.htm",
        "/EmployeeSiteGuide/EN/new_hire_during_enrollment_pd.htm",
        "/EmployeeSiteGuide/EN/use_home_page.htm",
        "/EmployeeSiteGuide/EN/review_dependents.htm",
        "/EmployeeSiteGuide/EN/eoi_home.htm",
        "/EmployeeSiteGuide/EN/current_coverage.htm",
        "/EmployeeSiteGuide/EN/past_coverage.htm",
        "/EmployeeSiteGuide/EN/incomplete_enrollment.htm",
        "/EmployeeSiteGuide/EN/modify_enrollment.htm",
        "/EmployeeSiteGuide/EN/student_status.htm",
        "/EmployeeSiteGuide/EN/other_forms.htm",
        "/EmployeeSiteGuide/EN/2FAActivate.htm",
        "/EmployeeSiteGuide/EN/forgot_password.htm",
        "/Dataload/dataload_intro.htm",
        "/Dataload/DL_onboard_new.htm",
        "/Dataload/employee.htm",
        "/Dataload/coverage.htm",
        "/Dataload/dependent.htm",
        "/Dataload/contingent_beneficiary.htm",
        "/Dataload/DL_support_existing.htm",
        "/Dataload/employee_flex_contribution.htm",
        "/Dataload/Update_employee_data.htm",
        "/Dataload/Update_employee.htm",
        "/Dataload/Payroll_adj_data.htm",
        "/Dataload/uploading_data.htm",
        "/Dataload/open_dataload.htm",
        "/Dataload/DL_upload_prep.htm",
        "/Dataload/UED_template.htm",
        "/Dataload/PAD_template.htm",
        "/Dataload/DL_upload.htm",
        "/Dataload/DL_validation.htm",
        "/Dataload/Processing.htm",
        "/Dataload/Proc_employee_data.htm",
        "/Dataload/Successfully_Processed.htm",
        "/Dataload/Processed_with_errors.htm",
        "/Dataload/Validation_errors.htm",
        "/Dataload/post_Processing.htm",
        "/Dataload/DL_template.htm",
        "/Dataload/Employee data import.htm",
        "/Dataload/Beneficiary data import.htm",
        "/Dataload/Coverage data import.htm",
        "/Dataload/Dependent data import.htm",
        "/Dataload/DL_Flex_contribution_acct.htm",
        "/Dataload/UED_fields.htm",
        "/Dataload/PAD_file_spec.htm",
    ]
}
